version: '3'

services:  
  kafka-rest:
    image: "confluentinc/cp-kafka-rest:3.2.1"
    network_mode: "host"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_REST_HOST_NAME: "localhost"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://localhost:8081"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
    ports:
      - "8082:8082"
  kafka-topics-ui:
    image: "landoop/kafka-topics-ui:0.9.2"
    environment:
      KAFKA_REST_PROXY_URL: "http://localhost:8082"
    ports:
      - "9002:8000"
    depends_on:
      - "kafka-rest"

  mysql:
    image: "mysql:5.7"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "jjug2017"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:4.7"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "password"
    ports:
      - "9003:80"
    depends_on:
      - "mysql"
